name: hawk
on:
  push:
    branches:
      - main
    paths:
      - '/v1.rb'

jobs:
  hawk:
    name: hawk
    runs-on: ubuntu-latest
    
    steps:
    - name: CommitHawk
      uses: jesalg/commit-hawk-action@v1.1
      with:
        slack_webhook_url: 'https://learner-ery7692.slack.com'
        slack_message: 'Contents of some important file(v1.rb) were changed on main'
